title: Blog
author: Minh Dang
# description: Minh Dang (aka minhhoccode111) - software developer - currently in love with Golang

collections:
  'blog':
    output: true
  'project':
    output: true

timezone: Asia/Ho_Chi_Minh
exclude:
  - README.md
