theme: jekyll-theme-minimal
title: Minh Dang
description: Minh Dang, also known as minhhoccode111, is a self-taught software developer. He has been working in web development since 2022 and is currently passionate about Linux, Vim, and Golang.
